project:
  type: website
  output-dir: docs

website:
  title: "My Website"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Report"
        href: report.qmd
      - text: "Visualizations for HW5"
        href: viz.qmd
    right:
      - icon: github
        href: https://github.com/JYW5114/JSC370-project
      - text: "My Project Home"
        href: https://github.com/JYW5114/JSC370-project
      - icon: file-earmark-pdf
        href: https://github.com/JYW5114/JSC370-project
      - text: "Full Report"
        href: https://github.com/JYW5114/JSC370-project
      - icon: escape
        href: https://github.com/JYW5114/JSC370-project
      - text: "Dashboard"
        href: https://jsc370-finalproject.onrender.com/
      #   target: _blank

  page-footer:
    center: "Copyright © 2026 Yiwei Jiang. All rights reserved."

format:
  html:
    theme: cosmo
    toc: true
    toc-float: true
    css: styles.css
