---
title: "Analysis of Factors Influencing Fire Incident Financial Loss in Toronto"
subtitle: "JSC370 Midterm Project Report"
author: "Yiwei Jiang"
format:
  html:
    toc: true
    embed-resources: true
    theme: cosmo
execute:
  echo: false
  warning: false
  message: false
jupyter: python3
---

## GitHub Repository
The complete reproducible pipeline, including data acquisition scripts and environment configurations, is available here:  
[**https://github.com/JYW5114/JSC370-project**](https://github.com/JYW5114/JSC370-project)

---

## Introduction

This project investigates the factors influencing Fire Incident Financial Loss within the City of Toronto. This metric is defined as the estimated dollar loss associated with a fire incident, including property damage and related losses. Understanding the drivers of financial loss is critical for optimizing urban resource allocation, improving fire prevention strategies, and minimizing economic impact.

**Research Questions:**
What factors influence the financial loss of fire incidents? How do weather conditions, property characteristics, and response resources relate to the severity of the loss? Are certain types of properties or incident types associated with higher losses?

**Research Hypothesis:**
The model predicts financial loss immediately after a fire is brought under control, before the official damage assessment is completed. We hypothesize that incident characteristics, property type, response resources, and weather conditions contain enough information to approximate the final financial loss. If successful, such predictions could provide an early estimate of economic impact and help prioritize post-incident response and resource allocation.

---

## Methods

### Data Acquisition
To satisfy the course requirement for dynamic data retrieval, I integrated two primary **API** sources:

1.  **Toronto Open Data API:** I retrieved the `fire-incidents` dataset by querying the CKAN datastore directly using the `requests` library. This dataset provides comprehensive logs of every fire emergency call from 2011-01-01 to 2024-12-31. Each record corresponds to a single incident and includes information about incident location, property characteristics, response resources, and fire suppression timelines.

2.  **Open-Meteo Historical Weather API:** I pulled hourly historical weather data (snowfall, temperature, and precipitation) for Toronto (Lat: 43.65, Lon: -79.38) to supplement the incident logs with environmental context.

### Data Cleaning & Wrangling

* **Preparation:** I used `dt.floor('H')` on the fire dataset to enable a precise `left join` with the weather API output. I filtered the dataset to include only incidents with non-missing `Estimated_Dollar_Loss` values and removed extreme outliers using a log-transform approach to stabilize variance. Variables like `Incident_Station_Area` contained a mix of integer and string types, so data type unification was performed. Because the dataset includes incidents other than fires (e.g., medical calls), the data was further filtered to retain fire-related incidents only.

* **Feature Engineering:** I derived `Hour_of_Day`, `is_weekend`, and `month` to capture temporal patterns. I also defined `Control_Duration` as the time elapsed from the arrival of Toronto Fire Services (TFS) personnel at an incident scene to the moment the fire is officially declared under control.

* **Preventing Data Leakage:** The full dataset was first split into training, validation, and testing sets. Exploratory analysis and model development were conducted only on the training data. In accordance with our research hypothesis, variables that become available after the fire is brought under control were excluded from the model, such as `Count_of_Persons_Rescued` and `Estimated_Number_Of_Persons_Displaced`. 

### Statistical Tools
Exploratory data analysis (EDA) was conducted using Python libraries including pandas, seaborn, matplotlib, and plotly. Summary statistics and visualizations were used to understand the distribution of fire caused loss and identify potential relationships between explanatory variables and the financial loss.

Several visualization techniques were applied:

* Histograms to analyze the distribution of the target and features

* Boxplots to examine relationships between categorical variables and the loss

* Line plots to explore relationships between continuous variables and identify potential periodic patterns

* Geographic maps to visualize the spatial distribution of fire incidents across Toronto  

For the final modeling stage, an XGBoost model will be implemented to predict fire caused loss based on incident characteristics, weather conditions, fire scales and response resources.

---

## Preliminary Results

This section presents exploratory findings based on the training dataset only, in order to prevent information leakage into the final modeling stage.

#### 1. Spatial distribution of fire in Toronto

As shown in @fig-fire-map, fire incidents in Toronto are generally spread across the city, although the downtown area exhibits the highest density of incidents. Most fires appear to be controlled relatively quickly. However, incidents associated with larger financial losses and longer control durations are more frequently observed in the downtown and northwestern areas.

In the visualization, point size represents the estimated financial loss, while color indicates the control duration. The plot suggests that the relationship between fire duration and financial loss is not straightforward. Some incidents with relatively short control durations still result in substantial financial damage, while fires that take longer to control do not necessarily lead to extremely large losses. This pattern indicates that additional factors beyond fire duration likely play an important role in determining the final financial impact of an incident.
```{python}
#| echo: false
#| eval: true
#| fig-cap: Spatial distribution of fire incidents in Toronto
#| label: fig-fire-map
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from sklearn.model_selection import train_test_split
from matplotlib.lines import Line2D
%matplotlib inline

df = pd.read_csv("fire.csv")
time_cols = ['TFS_Alarm_Time', 'TFS_Arrival_Time', 'Fire_Under_Control_Time', 'Hourly_Timestamp']
for col in time_cols:
    df[col] = pd.to_datetime(df[col])
df['Control_Duration'] = (df['Fire_Under_Control_Time'] - df['TFS_Arrival_Time']).dt.total_seconds()
df['Hour_of_Day'] = df['Hourly_Timestamp'].dt.hour
df['is_weekend'] = df['Hourly_Timestamp'].dt.dayofweek >= 5

def categorize_event(x):
    x = str(x)
    if "Fire" in x or x.startswith("FI"):
        return "Fire"
    else:
        return "Other"
df["Event_Category"] = df["Initial_CAD_Event_Type"].apply(categorize_event)
df = df[df["Event_Category"]=="Fire"]

df_train_val, df_test = train_test_split(df, test_size=0.2, random_state=42)
df_train, df_val = train_test_split(df_train_val, test_size=0.2, random_state=42)

df_analysis = df_train[(df_train['Control_Duration'] > 0) & (df_train['Control_Duration'] < 14400)].copy()
df_analysis['Incident_Station_Area'] = df_analysis['Incident_Station_Area'].astype(int)

df_map = df_analysis.dropna(subset=['Latitude', 'Longitude', 'Control_Duration', "Estimated_Dollar_Loss"])
df_map = df_map[df_map['Control_Duration'] < 7200]
fig = px.scatter_mapbox(df_map, 
                        lat="Latitude", 
                        lon="Longitude", 
                        color="Control_Duration", 
                        size="Estimated_Dollar_Loss",
                        color_continuous_scale=px.colors.cyclical.IceFire, 
                        size_max=15, 
                        zoom=10,
                        mapbox_style="carto-positron",
                        title="Fire distribution",
                        hover_data=['Final_Incident_Type', 'Property_Use'])
fig.show()
```

Note that because fire incident density is naturally higher in areas with greater population and building density, part of the spatial clustering observed in downtown Toronto may reflect urban structure rather than purely higher fire risk.

#### 2. Distribution of the financial loss

The overall distribution of financial loss is highly right-skewed, as shown in @fig-target. Most incidents result in relatively small losses, while a small number of fires lead to extremely large financial damages.

```{python}
#| echo: false
#| eval: true
#| fig-cap: Distribution of Estimated Dollar Loss
#| label: fig-target
#| fig-width: 8
#| fig-height: 6
plt.hist(df_analysis[df_analysis["Estimated_Dollar_Loss"] < 1e5]["Estimated_Dollar_Loss"], 
         bins=20, color='skyblue', edgecolor='black')

plt.title('Distribution of Estimated Dollar Loss')
plt.xlabel('Estimated Dollar Loss')
plt.ylabel('Number of Incidents')

plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()
```

To further summarize the key variables used in the analysis, @tbl-summary presents several descriptive statistics including the mean, median, standard deviation, and range.
```{python}
#| echo: false
#| eval: true
#| label: tbl-summary
#| tbl-cap: Summary statistics for key variables in the fire incident dataset
summary = df_analysis[[
    "Estimated_Dollar_Loss",
    "Control_Duration",
    "temperature_2m",
    "snowfall"
]].agg(["mean","median","std","min","max"]).T.round(2)

summary
```

Examining the monthly trend of fire-related losses in @fig-target-month reveals a recurring pattern across many years: a noticeable downward spike appears around the middle of the year, where total losses temporarily decrease before rising again. This suggests the presence of a potential seasonal or periodic effect. Overall, the total financial losses remain relatively stable throughout the study period, with a noticeable increase between 2018 and 2021, followed by a slight decrease from 2022 to 2024.

```{python}
#| echo: false
#| eval: true
#| fig-cap: Monthly Trend of Fire Caused Loss
#| label: fig-target-month
#| fig-width: 8
#| fig-height: 4
df_analysis["Year_Month"] = df_analysis["TFS_Alarm_Time"].dt.to_period("M")
monthly_loss = (
    df_analysis
    .groupby("Year_Month")["Estimated_Dollar_Loss"]
    .median()
    .reset_index()
)
monthly_loss["Year_Month"] = monthly_loss["Year_Month"].astype(str)
plt.figure(figsize=(14,6))
sns.lineplot(
    data=monthly_loss,
    x=range(len(monthly_loss)),
    y="Estimated_Dollar_Loss"
)
plt.yscale("log")
plt.xticks(
    ticks=range(0, len(monthly_loss), 12),
    labels=monthly_loss["Year_Month"][::12],
    rotation=45
)
plt.xlabel("Year")
plt.ylabel("Median Loss")
plt.title("Monthly Trend of Fire Caused Loss (2011-2024)")
plt.show()
```


#### 3. Temporal Features

By analyzing the relationship between month, temperature, and financial loss in @fig-mon-temp, a clear periodic pattern can be observed. Temperature follows a strong seasonal cycle across months, resulting in a strong correlation between the two predictors. This suggests that both variables capture similar seasonal information.

To avoid redundancy, temperature may be preferred as the primary feature, since it directly reflects environmental conditions rather than simply representing time within the year. This also helps reduce multicollinearity in the predictive model.

```{python}
#| echo: false
#| eval: true
#| fig-cap: Seasonal Pattern of Fire Loss and Temperature
#| label: fig-mon-temp

from matplotlib.lines import Line2D
df_analysis["Month"] = df_analysis["TFS_Alarm_Time"].dt.month
monthly_stats = (
    df_analysis
    .groupby("Month")
    .agg(
        median_loss=("Estimated_Dollar_Loss", "median"),
        mean_temperature=("temperature_2m", "mean")
    )
    .reset_index()
)
fig, ax1 = plt.subplots(figsize=(10,6))
line1 = sns.lineplot(
    data=monthly_stats,
    x="Month",
    y="median_loss",
    marker="o",
    ax=ax1,
    color="tab:blue"
)

ax1.set_yscale("log")
ax1.set_xlabel("Month")
ax1.set_ylabel("Median Estimated_Dollar_Loss", color="tab:blue")
ax1.set_xticks(range(1,13))
ax1.set_title("Seasonal Pattern of Fire Estimated_Dollar_Loss and Temperature")
ax1.tick_params(axis='y', labelcolor="tab:blue")

ax2 = ax1.twinx()
line2 = sns.lineplot(
    data=monthly_stats,
    x="Month",
    y="mean_temperature",
    marker="s",
    linestyle="--",
    ax=ax2,
    color="tab:red"
)

ax2.set_ylabel("Average Temperature (°C)", color="tab:red")
ax2.tick_params(axis='y', labelcolor="tab:red")
legend_elements = [
    Line2D([0], [0], color="tab:blue", marker="o", label="Median Estimated_Dollar_Loss"),
    Line2D([0], [0], color="tab:red", marker="s", linestyle="--", label="Average Temperature")
]
ax1.legend(handles=legend_elements, loc="upper left")

plt.grid(alpha=0.3)
plt.show()
```

@fig-day reveals diurnal variations in fire-related dollar losses, with incidents occurring during the night showing a higher median loss. To represent this cyclical nature effectively, encoding the 'Hour of Day' as a periodic variable using sine and cosine transformations may help. This technique maps the temporal data into a circular space, ensuring the model captures the continuity between 23:00 and 00:00.
```{python}
#| echo: false
#| eval: true
#| fig-cap: Daily Pattern of Fire Loss
#| label: fig-day
#| fig-width: 8
#| fig-height: 4
plt.figure(figsize=(10,5))
sns.lineplot(
    data=df_analysis,
    x="Hour_of_Day",
    y="Estimated_Dollar_Loss",
    estimator="median",
    errorbar=None,
    marker="o"
)
plt.yscale("log")
plt.xticks(range(24))
plt.xlabel("Hour of Day")
plt.ylabel("Median Estimated_Dollar_Loss")
plt.title("Fire Caused Loss by Hour of Day")
plt.grid(alpha=0.3)
plt.show()
```


#### 4. Weather Effects

The weather also appears to influence the loss. @fig-snow shows a slight increase in financial loss when snowfall reaches moderate or higher levels. Snow may slow response times or create additional operational challenges, potentially allowing fires to spread before they are fully controlled. Similarly, modest patterns can be observed for precipitation, with higher rainfall generally associated with somewhat increased losses.

```{python}
#| echo: false
#| eval: true
#| fig-cap: Impact of Snowfall on Loss
#| label: fig-snow
#| fig-width: 8
#| fig-height: 6
df_analysis['Snow_Level'] = pd.cut(df_analysis['snowfall'], 
                                   bins=[-1, 0, 2, 5], 
                                   labels=['None', 'Light', 'Moderate'])

plt.figure(figsize=(10, 6))
sns.boxplot(data=df_analysis, x='Snow_Level', y='Estimated_Dollar_Loss')
plt.title('Impact of Snowfall Severity on Estimated_Dollar_Loss')
plt.yscale('log')
plt.show()
```


#### 5. Fire Suppression Resources and Property Uses

Here, incident scale is defined by the number of responding apparatus: "Small" (≤ 5) and "Large" (> 5).
As shown in @fig-resource, the "No sprinkler system" group shows the most significant surge in median loss as the incident scales up. Interestingly, "Full sprinkler system" group has higher increase related to the scales. This is likely because buildings equipped with full sprinkler systems are often larger, high-value commercial or multi-residential structures.

```{python}
#| echo: false
#| eval: true
#| fig-cap: Interaction between Sprinkler Presence and Incident Scale
#| label: fig-resource
order = [
    '9 - Undetermined', 
    '3 - No sprinkler system', 
    '2 - Partial sprinkler system present', 
    '1 - Full sprinkler system present'
]
df_analysis['Scale'] = df_analysis['Number_of_responding_apparatus'].apply(lambda x: 'Small' if x <= 5 else 'Large')

plt.figure(figsize=(14, 8))
sns.boxplot(
    data=df_analysis, 
    x='Sprinkler_System_Presence', 
    y='Estimated_Dollar_Loss', 
    hue='Scale',
    order=order,
    showfliers=False
)
plt.title('Impact of Sprinkler Presence on Estimated_Dollar_Loss: Grouped by Incident Scale')
plt.xticks(rotation=15)
plt.yscale("log")
plt.show()
```

The top 4 Property Uses are selected, the rest are combined into category "Others". In most of the categories, like Multi-Unit Dwellings, the jump from "Small" to "Large" scale results in a dramatic escalation of loss due to high asset density. Conversely, for Trash/Garbage fires, the loss is minimal regardless of scale, and the loss even decreases with fire scale.

```{python}
#| echo: false
#| eval: true
#| fig-cap: Horizontal Comparison of Median Loss
#| label: fig-prop-scale-h
top_property = df_analysis["Property_Use"].value_counts().nlargest(4).index

df_analysis["Property_Group"] = df_analysis["Property_Use"].where(
    df_analysis["Property_Use"].isin(top_property),
    "Other"
)
order = [
    '848 - Trash/Rubbish/Garbage Container or Dumpster',
    '302 - Semi-Detached Dwelling', 
    '301 - Detached Dwelling',
    '323 - Multi-Unit Dwelling - Over 12 Units', 
    'Other'
]

plt.figure(figsize=(8, 6))

sns.barplot(
    data=df_analysis, 
    y='Property_Group',
    x='Estimated_Dollar_Loss',
    hue='Scale', 
    estimator='median',
    order=order,
    errorbar=None,
    palette="viridis"
)

plt.xscale('log')
plt.title('Median Financial Loss by Property Group and Incident Scale')
plt.xlabel('Median Estimated Dollar Loss (Log Scale)')
plt.ylabel('Property Group')
plt.legend(title='Incident Scale')

plt.grid(axis='x', linestyle='--', alpha=0.3)
plt.tight_layout()
plt.show()
```

## Summary
Based on the exploratory analysis, several key insights emerge:

* Financial Loss Distribution: Most fire incidents are resolved quickly and do not cost much, but the distribution is highly right-skewed, with a small number of incidents result in disproportionately large financial damages.

* Temporal Patterns: Fire caused loss varies by hour of the day and season. Incidents occurring during night hours or in colder months tend to have larger median loss, reflecting operational challenges such as low visibility, icy roads, or increased response complexity.

* Weather Impact: Snowfall and lower temperatures are associated with larger loss. In particular, medium to heavy snowfall correlates with noticeable increases in the fire caused loss.

* Response Resources: Incident scale is a primary driver of loss, but its impact is moderated by response resources like suppression systems.

* Property-Specific Sensitivity: Residential buildings appear particularly sensitive to fire magnitude. In contrast, refuse-related fires (e.g., trash containers) maintain minimal financial impact regardless of response scale.


## Plan for Final Project
For the final phase of this project, I will develop a predictive modeling framework and an interactive platform to explore fire incident financial loss in Toronto:

* Machine Learning Modeling (XGBoost): I will implement an XGBoost Regressor to predict `Estimated_Dollar_Loss`. XGBoost is selected for its superior ability to capture non-linear interactions and handle categorical features. Hyperparameters will be optimized using a grid search on the validation set. The model will be evaluated using metrics such as RMSE and R^2, and feature importance will be analyzed to identify the most influential factors driving fire losses.

* Interactive Visualization: I plan to build a comprehensive dashboard where users can explore historical fire incidents via an interactive map.

* Predictive Simulator: The website will include a predictive simulator where users can select a location, adjust parameters (e.g., snowfall, temperature, time of day, number of responding personnel, control duration), and receive an estimated financial loss. Scenario comparisons will allow users to explore “what-if” situations and understand how different factors affect outcomes.

* Insights and Guidance: In addition to predictions, the platform will highlight key risk factors and provide guidance for decision-making, such as high-risk areas or conditions associated with greater financial loss.