---
title: "Visualizations for HW5"
author: "Yiwei Jiang"
format:
  html:
    code-fold: true
    embed-resources: true
    interactive: true
    toc: true
    theme: cosmo
execute:
  echo: false
  warning: false
  message: false
jupyter: python3
---

### 1. Spatial distribution of fire in Toronto by Year

In the visualization, point size represents the estimated financial loss, while color indicates the control duration. The slider controls the specific year from 2011 to 2024. Hovering over the point, the estimated dollar loss, property type and exact location are provided.
```{python}
#| echo: false
#| eval: true
#| fig-cap: Spatial distribution of fire incidents in Toronto
#| label: fig-fire-map
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from sklearn.model_selection import train_test_split
from matplotlib.lines import Line2D
%matplotlib inline
import ipywidgets as widgets
from IPython.display import display

df = pd.read_csv("fire.csv", low_memory=False)
time_cols = ['TFS_Alarm_Time', 'TFS_Arrival_Time', 'Fire_Under_Control_Time', 'Hourly_Timestamp']
for col in time_cols:
    df[col] = pd.to_datetime(df[col])
df['Control_Duration'] = (df['Fire_Under_Control_Time'] - df['TFS_Arrival_Time']).dt.total_seconds()
df['Hour_of_Day'] = df['Hourly_Timestamp'].dt.hour
df['is_weekend'] = df['Hourly_Timestamp'].dt.dayofweek >= 5

def categorize_event(x):
    x = str(x)
    if "Fire" in x or x.startswith("FI"):
        return "Fire"
    else:
        return "Other"
df["Event_Category"] = df["Initial_CAD_Event_Type"].apply(categorize_event)
df = df[df["Event_Category"]=="Fire"]

df_train_val, df_test = train_test_split(df, test_size=0.2, random_state=42)
df_train, df_val = train_test_split(df_train_val, test_size=0.2, random_state=42)

df_analysis = df_train[(df_train['Control_Duration'] > 0) & (df_train['Control_Duration'] < 14400)].copy()
df_analysis['Incident_Station_Area'] = df_analysis['Incident_Station_Area'].astype(int)

df_map = df_analysis.dropna(subset=['Latitude', 'Longitude', 'Control_Duration', "Estimated_Dollar_Loss"])
df_map = df_map[df_map['Control_Duration'] < 7200]
df_map["Year"] = df_map["TFS_Alarm_Time"].dt.year

year_order = sorted(df_map["Year"].unique())

fig = px.scatter_mapbox(
    df_map,
    lat="Latitude",
    lon="Longitude",
    color="Control_Duration",
    size="Estimated_Dollar_Loss",
    animation_frame="Year",
    category_orders={"Year": year_order},
    hover_name="Final_Incident_Type",
    hover_data=["Property_Use", "Estimated_Dollar_Loss"],
    mapbox_style="carto-positron",
    zoom=10
)

fig.show()
```

As shown in @fig-fire-map, fire incidents in Toronto are generally spread across the city, although the downtown area exhibits the highest density of incidents. Most fires appear to be controlled relatively quickly. However, incidents associated with larger financial losses and longer control durations are more frequently observed in the downtown and northwestern areas.

The plot suggests that the relationship between fire duration and financial loss is not straightforward. Some incidents with relatively short control durations still result in substantial financial damage, while fires that take longer to control do not necessarily lead to extremely large losses. This pattern indicates that additional factors beyond fire duration likely play an important role in determining the final financial impact of an incident.


### 2. Interaction between Property Type, Sprinkler System, and Fire Scale

This visualization presents a parallel categories (Sankey) plot, which is used to examine how multiple categorical variables jointly interact and influence fire loss outcomes. Specifically, the plot links three key dimensions of fire incidents in Toronto:

- Property_Group_Plot (property type: Residential, Commercial, Other)
- Sprinkler_System_Presence (fire suppression system level)
- Scale (incident response scale)

Each path in the diagram represents a combination of these attributes, while the color encoding reflects the Loss_Level (Low, Medium, High).
```{python}
#| echo: false
#| eval: true
#| fig-cap: Sankey
#| label: fig-sankey

df_analysis['Scale'] = df_analysis['Number_of_responding_apparatus'].apply(lambda x: 'Small' if x <= 10 else 'Large')
def categorize_property(x):
    if pd.isna(x):
        return "Other"
    
    code = x.split(" - ")[0].strip()
    
    residential = {"301", "302", "303", "321", "322", "323", "311", "331"}
    commercial = {"151", "501", "405", "334"}
    vehicles = {"901", "902", "903", "837"}
    garages = {"365", "603"}
    infra = {"896", "144", "846", "891"}
    waste = {"848"}
    
    if code in residential:
        return "Residential"
    elif code in commercial:
        return "Commercial"
    elif code in vehicles:
        return "Vehicles"
    elif code in infra:
        return "Infrastructure"
    elif code in waste:
        return "Waste"
    elif code in garages:
        return "Garages"
    else:
        return "Other"
    
df_analysis["Property_Group"] = df_analysis["Property_Use"].apply(categorize_property)
df_analysis["Loss_Level"] = pd.qcut( df_analysis["Estimated_Dollar_Loss"], q=3, labels=["Low", "Medium", "High"] )

df_analysis["Sprinkler_System_Presence"] = df_analysis["Sprinkler_System_Presence"].fillna("9 - Undetermined")
loss_map = {"Low": 0, "Medium": 1, "High": 2}

main_groups = ["Residential", "Commercial"]

df_analysis["Property_Group_Plot"] = df_analysis["Property_Group"].where(
    df_analysis["Property_Group"].isin(main_groups),
    "Other"
)

df_analysis["Scale"] = pd.Categorical(
    df_analysis["Scale"],
    categories=["Small", "Medium", "Large"],
    ordered=True
)

# sprinkler_selector = widgets.Dropdown(
#     options=[
#         "All",
#         "1 - Full sprinkler system present",
#         "2 - Partial sprinkler system present",
#         "3 - No sprinkler system"
#     ],
#     value="All",
#     description="Sprinkler"
# )

# property_selector = widgets.Dropdown(
#     options=["All"] + sorted(df_analysis["Property_Group_Plot"].dropna().unique()),
#     value="All",
#     description="Property"
# )

# color_toggle = widgets.Checkbox(
#     value=True,
#     description="Color by Loss"
# )

# def update_plot(sprinkler, property_group, color_by_loss):

#     df = df_analysis.copy()

#     # remove undetermined
#     df = df[df["Sprinkler_System_Presence"] != "9 - Undetermined"]

#     # filter sprinkler
#     if sprinkler != "All":
#         df = df[df["Sprinkler_System_Presence"] == sprinkler]

#     if property_group != "All":
#         df = df[df["Property_Group_Plot"] == property_group]

#     # color logic
#     if color_by_loss:
#         color = df["Loss_Level"].map(loss_map)
#         color_scale = ["green", "orange", "red"]
#     else:
#         color = None
#         color_scale = None

#     fig = px.parallel_categories(
#         df,
#         dimensions=[
#             "Property_Group_Plot",
#             "Sprinkler_System_Presence",
#             "Scale",
#         ],
#         color=color,
#         color_continuous_scale=color_scale
#     )

#     fig.update_layout(
#         width=1200,
#         height=500,
#         margin=dict(l=100, r=100, t=50, b=50),
#         font=dict(size=12)
#     )

#     if color_by_loss:
#         fig.update_coloraxes(
#             colorbar=dict(
#                 title="Loss Level",
#                 tickvals=[0, 1, 2],
#                 ticktext=["Low", "Medium", "High"],
#                 x=1.1,
#                 len=0.8
#             )
#         )

#     fig.show()

# ui = HBox([sprinkler_selector, property_selector, color_toggle])

# out = interactive_output(
#     update_plot,
#     {
#         "sprinkler": sprinkler_selector,
#         "property_group": property_selector,
#         "color_by_loss": color_toggle
#     }
# )

# display(ui, out)

df = df_analysis.copy()
df = df[df["Sprinkler_System_Presence"] != "9 - Undetermined"]

loss_map = {"Low": 0, "Medium": 1, "High": 2}

sprinklers = {
    "All": None,
    "Full": "1 - Full sprinkler system present",
    "Partial": "2 - Partial sprinkler system present",
    "No": "3 - No sprinkler system"
}

properties = ["All", "Residential", "Commercial", "Other"]

combo_data = {}

for s_name, s_val in sprinklers.items():
    for p in properties:

        key = (s_name, p)

        dff = df.copy()

        if s_val is not None:
            dff = dff[dff["Sprinkler_System_Presence"] == s_val]

        if p != "All":
            dff = dff[dff["Property_Group_Plot"] == p]

        combo_data[key] = dff

init_df = combo_data[("All", "All")]

fig = px.parallel_categories(
    init_df,
    dimensions=[
        "Property_Group_Plot",
        "Sprinkler_System_Presence",
        "Scale",
    ],
    color=init_df["Loss_Level"].map(loss_map),
    color_continuous_scale=["#f8cdda", "#f06292", "#6a1b9a"]
)

def make_args(s_name, p):
    dff = combo_data[(s_name, p)]
    return {
        "dimensions[0].values": [dff["Property_Group_Plot"]],
        "dimensions[1].values": [dff["Sprinkler_System_Presence"]],
        "dimensions[2].values": [dff["Scale"]],
        "line.color": [dff["Loss_Level"].map(loss_map)]
    }

sprinkler_buttons = []
for s in sprinklers.keys():
    sprinkler_buttons.append(
        dict(
            label=s,
            method="update",
            args=[make_args(s, "All")]
        )
    )

property_buttons = []
for p in properties:
    property_buttons.append(
        dict(
            label=p,
            method="update",
            args=[make_args("All", p)]
        )
    )

fig.update_layout(
    updatemenus=[
        dict(
            buttons=sprinkler_buttons,
            direction="down",
            x=0.3,
            y=1.15,
            showactive=True,
            xanchor="left",
            yanchor="top"
        ),
        dict(
            buttons=property_buttons,
            direction="down",
            x=0.6,
            y=1.15,
            showactive=True,
            xanchor="left",
            yanchor="top"
        )
    ],
    annotations=[
        dict(
            text="Sprinkler System",
            x=0.25,
            y=1.25,
            xref="paper",
            yref="paper",
            showarrow=False,
            font=dict(size=13)
        ),
        dict(
            text="Property Type",
            x=0.55,
            y=1.25,
            xref="paper",
            yref="paper",
            showarrow=False,
            font=dict(size=13)
        )
    ],
    width=1200,
    height=500,
    margin=dict(l=100, r=150, t=100, b=50),
    font=dict(size=12)
)


fig.update_coloraxes(
    colorbar=dict(
        title="Loss Level",
        tickvals=[0, 1, 2],
        ticktext=["Low", "Medium", "High"],
        x=1.1
    )
)

fig.show()
```

@fig-sankey allows users to examine the data from different perspectives:

* Sprinkler System (All vs. specific types)
- All: displays the full structure across all sprinkler conditions, revealing general interaction patterns.
- Full / Partial / No: isolates specific system conditions to evaluate how suppression level changes the relationship.

* Property Type (All vs. specific categories)
- All: provides a global overview across Residential, Commercial, and Other property types.
- Residential / Commercial / Other: isolates structural differences within each property category.

The underlying risk of a specific fire scale is approximately similarly distributed across the three property groups. In general, larger-scale incidents are more likely to be associated with higher financial losses. Properties equipped with sprinkler systems tend to exhibit a relatively lower risk of generating large losses.

In Residential and Commercial groups, as fire suppression improves from No tp Partial and to Full sprinkler coverage, the proportion of high-loss (red) outcomes decreases in cases of large scale. This suggests that sprinkler systems play a strong mitigating role in reducing severe financial loss when incidents escalate. However, this relationship is not equally evident in the Other property category. 


```{python}

```